[profile.default]
src = "src"
test = "test"
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
libs = ["../../nana-core-v6/node_modules", "../../nana-core-v6/lib"]

[profile.default.fuzz]
runs = 512

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
