/** Plain-language explanations for the simulator's editable assumptions. */
export const FIELD_HELP = Object.freeze({
  purchaseBudget: 'The amount needed to buy the asset. The fundraising goal also includes the cash reserve, purchase costs, and assumed payout fee.',
  opsReserve: 'Extra cash raised to help pay operating expenses while income builds up. Any unused reserve is shared with FUND holders if the asset is sold.',
  monthlyRent: 'Total revenue expected each month in year one, before operating expenses. Annual revenue growth changes this amount in later years.',
  monthlyCosts: 'Money needed each month in year one to run the asset, including maintenance, taxes, insurance and management.',
  raisedPercent: 'How much of the total fundraising goal has been contributed so far. Changing this only previews a stage of the raise.',
  revenueMonths: 'How many months of revenue to include after the asset purchase. In the sale preview, this is also the month the asset is sold.',
  closingCosts: 'Additional costs paid when buying the asset, beyond its price. These increase the fundraising goal.',
  precloseSpent: 'Money already spent from investor contributions before the purchase. It increases the total amount that must be raised and reduces the cash left for refunds if the raise fails.',
  payoutFeePercent: 'The assumed Juicebox fee on money paid out at closing; the actual fee depends on how the payment is sent. The goal increases to cover it so the asset, reserve, and purchase costs receive their planned amounts.',
  operatorFundPercent: 'The operator’s share of all FUND after the purchase completes. At 20%, investors hold the other 80% of the claim on net asset-sale cash.',
  revenuePremint: 'Total INCOME tokens created once when the asset purchase completes. They are divided among all FUND holders, including the operator, and do not represent cash already earned.',
  stickySplitPercent: 'Share of new INCOME automatically allocated to FUND holders in proportion to their holdings. No staking is required.',
  stickyVestingMonths: 'The simulated wait before staking rewards become available to cash out or use for a loan. The model collects them after this delay; the live weekly reward schedule differs.',
  otherStakePercent: 'Share of other holders’ FUND assumed staked throughout the simulation, including the operator’s FUND. More participation can reduce your share of the staking rewards.',
  revPrice: 'Starting amount of revenue received for each new INCOME token. At $0.10, each $1 of revenue creates 10 INCOME; this does not set their cash-out value.',
  operatorSplitPercent: 'Share of new INCOME tokens given directly to the operator during the first 12 months. This is a token allocation, not a percentage of revenue paid out in cash.',
  ongoingOperatorSplitPercent: 'Share of new INCOME tokens given directly to the operator from month 13 onward. The operator also receives the holder allocation on its own FUND.',
  issuanceCutPercent: 'How much new INCOME per revenue dollar falls at each scheduled cut. The default is 5% each quarter: 10 tokens per dollar becomes 9.5 after the first quarter.',
  issuanceCutMonths: 'Months between reductions in INCOME per revenue dollar. Three months means one quarter.',
  issuanceCutYears: 'How long issuance reductions continue. At one cut each quarter for two years, there are eight cuts, then issuance stays fixed.',
  rentGrowthPercent: 'How much monthly revenue changes at the start of each new year. At 3%, $10,000 per month becomes $10,300 in year two.',
  costGrowthPercent: 'How much monthly operating costs change at the start of each new year. At 3%, $6,000 per month becomes $6,180 in year two.',
  renterCashoutPercent: 'Share of each month’s new customer INCOME that customers immediately cash out after the operator’s cash-out. Customers’ older tokens remain held in this scenario.',
  revCashoutFeePercent: 'Fee assumption for operator and customer cash-outs, used to test how fees affect operating cash. Your cash-out quote stays before fees; loan fees are calculated separately.',
  salePrice: 'Assumed price if the asset is sold, before selling costs and debt. The asset’s value does not count as cash backing INCOME tokens.',
  saleCostPercent: 'Share of the sale price used for selling expenses, such as agent and legal fees. At 5%, a $500,000 sale has $25,000 of selling costs.',
  saleDebt: 'Debt and other senior claims paid from the sale before FUND holders receive cash. The model deducts unpaid operating costs separately.',
  investment: 'Your contribution to this asset’s raise, included in the total already raised. It determines your FUND allocation and your share of the initial INCOME tokens.',
  personalStakePercent: 'The portion of your FUND you stake to earn extra INCOME tokens. 100% means all your FUND; 0% means none. Your share of asset-sale proceeds stays the same either way.',
});
